### PR TITLE
*: Modified to conform to Module aware 'go list'

### PR DESCRIPTION
**Pull request by vimalk78**
modified to use go1.13

### CODE REVIEW

**Comment by vimalk78** [comment]
fixes https://github.com/etcd-io/etcd/issues/11132

**Comment by vimalk78** [comment]
@gyuho PTAL

**Comment by gyuho** [comment]
Does this fix the issue? /cc @philips

**Comment by philips** [comment]
can you update the commit message of 038a5eba3d6f54c1c47df54fda27460b5ca2c97d to include some details on what this change is and why it was necessary for go 1.13

Here is an example of a good commit message from this repo: https://github.com/coreos/license-bill-of-materials/commit/55ffe162dfc243e5f0f044daf3ba86fa488f1db4

Some more context: 
https://juffalow.com/other/write-good-git-commit-message

**Comment by vimalk78** [comment]
@philips thanks for the comment. Updated the commit message. 
Please have a look.

**Comment by philips** [comment]
LGTM, go for it.

**Comment by vimalk78** [comment]
can this PR be merged?

**Comment by vimalk78** [comment]
thanks @philips !!

**Pull request merged**
